/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const IndexLazyRouteImport = createFileRoute('/')()
const ProductProductSlugLazyRouteImport = createFileRoute(
  '/product/$productSlug',
)()
const CategoryCategoryLazyRouteImport = createFileRoute('/category/$category')()

const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const ProductProductSlugLazyRoute = ProductProductSlugLazyRouteImport.update({
  id: '/product/$productSlug',
  path: '/product/$productSlug',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/product/$productSlug.lazy').then((d) => d.Route),
)
const CategoryCategoryLazyRoute = CategoryCategoryLazyRouteImport.update({
  id: '/category/$category',
  path: '/category/$category',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/category/$category.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/category/$category': typeof CategoryCategoryLazyRoute
  '/product/$productSlug': typeof ProductProductSlugLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/category/$category': typeof CategoryCategoryLazyRoute
  '/product/$productSlug': typeof ProductProductSlugLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/category/$category': typeof CategoryCategoryLazyRoute
  '/product/$productSlug': typeof ProductProductSlugLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/category/$category' | '/product/$productSlug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/category/$category' | '/product/$productSlug'
  id: '__root__' | '/' | '/category/$category' | '/product/$productSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  CategoryCategoryLazyRoute: typeof CategoryCategoryLazyRoute
  ProductProductSlugLazyRoute: typeof ProductProductSlugLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$productSlug': {
      id: '/product/$productSlug'
      path: '/product/$productSlug'
      fullPath: '/product/$productSlug'
      preLoaderRoute: typeof ProductProductSlugLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$category': {
      id: '/category/$category'
      path: '/category/$category'
      fullPath: '/category/$category'
      preLoaderRoute: typeof CategoryCategoryLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  CategoryCategoryLazyRoute: CategoryCategoryLazyRoute,
  ProductProductSlugLazyRoute: ProductProductSlugLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
