/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const IndexLazyRouteImport = createFileRoute('/')()
const CategoryIndexLazyRouteImport = createFileRoute('/$category/')()
const CategoryProductLazyRouteImport = createFileRoute('/$category/$product')()

const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const CategoryIndexLazyRoute = CategoryIndexLazyRouteImport.update({
  id: '/$category/',
  path: '/$category/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/$category/index.lazy').then((d) => d.Route),
)
const CategoryProductLazyRoute = CategoryProductLazyRouteImport.update({
  id: '/$category/$product',
  path: '/$category/$product',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/$category/$product.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/$category/$product': typeof CategoryProductLazyRoute
  '/$category/': typeof CategoryIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/$category/$product': typeof CategoryProductLazyRoute
  '/$category': typeof CategoryIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/$category/$product': typeof CategoryProductLazyRoute
  '/$category/': typeof CategoryIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$category/$product' | '/$category/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$category/$product' | '/$category'
  id: '__root__' | '/' | '/$category/$product' | '/$category/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  CategoryProductLazyRoute: typeof CategoryProductLazyRoute
  CategoryIndexLazyRoute: typeof CategoryIndexLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$category/': {
      id: '/$category/'
      path: '/$category'
      fullPath: '/$category/'
      preLoaderRoute: typeof CategoryIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$category/$product': {
      id: '/$category/$product'
      path: '/$category/$product'
      fullPath: '/$category/$product'
      preLoaderRoute: typeof CategoryProductLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  CategoryProductLazyRoute: CategoryProductLazyRoute,
  CategoryIndexLazyRoute: CategoryIndexLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
