/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const IndexLazyRouteImport = createFileRoute('/')()
const ProductProductLazyRouteImport = createFileRoute('/product/$product')()
const CategoryCategoryLazyRouteImport = createFileRoute('/category/$category')()

const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const ProductProductLazyRoute = ProductProductLazyRouteImport.update({
  id: '/product/$product',
  path: '/product/$product',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/product/$product.lazy').then((d) => d.Route),
)
const CategoryCategoryLazyRoute = CategoryCategoryLazyRouteImport.update({
  id: '/category/$category',
  path: '/category/$category',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/category/$category.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/category/$category': typeof CategoryCategoryLazyRoute
  '/product/$product': typeof ProductProductLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/category/$category': typeof CategoryCategoryLazyRoute
  '/product/$product': typeof ProductProductLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/category/$category': typeof CategoryCategoryLazyRoute
  '/product/$product': typeof ProductProductLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/category/$category' | '/product/$product'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/category/$category' | '/product/$product'
  id: '__root__' | '/' | '/category/$category' | '/product/$product'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  CategoryCategoryLazyRoute: typeof CategoryCategoryLazyRoute
  ProductProductLazyRoute: typeof ProductProductLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$product': {
      id: '/product/$product'
      path: '/product/$product'
      fullPath: '/product/$product'
      preLoaderRoute: typeof ProductProductLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$category': {
      id: '/category/$category'
      path: '/category/$category'
      fullPath: '/category/$category'
      preLoaderRoute: typeof CategoryCategoryLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  CategoryCategoryLazyRoute: CategoryCategoryLazyRoute,
  ProductProductLazyRoute: ProductProductLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
